version: "3"

services:

  franz-manager:
    image: greencomnetworks/franz-manager
    restart: on-failure
    environment:
      - FRONT_BASEPATH
      - SERVER_URL=${SERVER_URL?SERVER_URL missing}
      - WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL?WEBSOCKET_SERVER_URL missing}
    ports:
      - 80:80
    depends_on:
      - franz-manager-api

  franz-manager-api:
    image: greencomnetworks/franz-manager-api
    restart: on-failure
    environment:
      - LOG_LEVEL
      - JVM_HEAP_SIZE
      - API_LISTENER_WORKERS_CORE
      - API_LISTENER_WORKERS_MAX
      - API_BASEPATH
      - API_PORT=8080
      - WS_PORT=8081
      - KAFKA_CONF=${KAFKA_CONF:?KAFKA_CONF missing}
    ports:
      - ${API_PORT:-8080}:${API_PORT:-8080}
      - ${WS_PORT:-8081}:${WS_PORT:-8081}
